-- backend/models/seeds/job_sources.seed.sql
-- Generated from VFL_Law_Job_Internship_Sites_Deduped_1.pdf and court links.pdf
-- 84 curated portals/firms/NGOs/edtech (source PDF's own header says 94; only 84 rows actually exist after
--   numbers 21-30 were dropped for Naukri/LinkedIn/Indeed/aggregators, per the PDF's own notes) +
--   26 Supreme/High Courts + 675 district courts via eCourts = 785 total sources
-- Re-runnable: ON CONFLICT (url) DO NOTHING

INSERT INTO job_sources (name, url, category, scrape_method) VALUES
  ('Lawctopus', 'https://www.lawctopus.com/category/opportunities-events/internships-small-projects/', 'portal', 'direct'),
  ('LawBhoomi Internships', 'https://lawbhoomi.com/category/internship-opportunities/', 'portal', 'direct'),
  ('Neeti Shastra', 'https://neetishastra.com/', 'portal', 'direct'),
  ('LiveLaw Law School', 'https://www.livelaw.in/lawschool/internships', 'portal', 'direct'),
  ('Bar & Bench Law Firms', 'https://www.barandbench.com/law-firms', 'portal', 'direct'),
  ('Legally India', 'https://www.legallyindia.com/', 'portal', 'direct'),
  ('Legal Service India Jobs', 'https://www.legalserviceindia.com/legal/jobs.html', 'portal', 'direct'),
  ('The LawCademy', 'https://thelawcademy.in/law_resources/', 'portal', 'direct'),
  ('Manupatra Academy Internships', 'https://www.manupatracademy.com/internships/law-student-opportunities', 'portal', 'direct'),
  ('LegalHires', 'https://www.legalhires.com/', 'portal', 'direct'),
  ('LawyersClubIndia Jobs', 'https://www.lawyersclubindia.com/jobs/', 'portal', 'direct'),
  ('Vidhikarya Legal Jobs', 'https://www.vidhikarya.com/legal-jobs', 'portal', 'direct'),
  ('LexPeeps', 'https://lexpeeps.in/', 'portal', 'direct'),
  ('Legalstix', 'https://legalstix.in/', 'portal', 'direct'),
  ('SCC Online Blog Careers', 'https://www.scconline.com/blog/', 'portal', 'direct'),
  ('MyAdvo', 'https://www.myadvo.in/', 'portal', 'direct'),
  ('Bhartiya Lawyer', 'https://bhartiyalawyer.com/', 'portal', 'direct'),
  ('LegalWires', 'https://legalwires.in/', 'portal', 'direct'),
  ('Lawtsapp', 'https://lawtsapp.com/', 'portal', 'direct'),
  ('Law Insider India', 'https://www.lawinsider.in/', 'portal', 'direct'),
  ('NALSA (National Legal Services Authority)', 'https://nalsa.gov.in/', 'government', 'direct'),
  ('Dept. of Justice, Govt. of India', 'https://doj.gov.in/', 'government', 'direct'),
  ('UPSC', 'https://upsc.gov.in/', 'government', 'direct'),
  ('SSC (Staff Selection Commission)', 'https://ssc.nic.in/', 'government', 'direct'),
  ('eCourts India', 'https://ecourts.gov.in/', 'government', 'direct'),
  ('Bar Council of India', 'https://www.barcouncilofindia.org/', 'government', 'direct'),
  ('Delhi State Legal Services Authority', 'https://dslsa.org/', 'government', 'direct'),
  ('Maharashtra State Legal Services Authority', 'https://mslsa.maharashtra.gov.in/', 'government', 'direct'),
  ('Kerala State Legal Services Authority', 'https://kelsa.nic.in/', 'government', 'direct'),
  ('Tamil Nadu State Legal Services Authority', 'https://tnlsa.tn.gov.in/', 'government', 'direct'),
  ('National Human Rights Commission', 'https://nhrc.nic.in/', 'government', 'direct'),
  ('Ministry of Law and Justice', 'https://lawmin.gov.in/', 'government', 'direct'),
  ('Cyril Amarchand Mangaldas', 'https://www.cyrilshroff.com/careers/', 'law_firm', 'direct'),
  ('Khaitan & Co.', 'https://www.khaitanco.com/careers', 'law_firm', 'direct'),
  ('Trilegal', 'https://trilegal.com/internship/', 'law_firm', 'direct'),
  ('AZB & Partners', 'https://www.azbpartners.com/careers/', 'law_firm', 'direct'),
  ('J. Sagar Associates (JSA)', 'https://www.jsalaw.com/careers/', 'law_firm', 'direct'),
  ('Shardul Amarchand Mangaldas', 'https://www.shardulamarchand.com/careers', 'law_firm', 'direct'),
  ('IndusLaw', 'https://induslaw.com/careers/', 'law_firm', 'direct'),
  ('Phoenix Legal', 'https://www.phoenixlegal.in/internship.php', 'law_firm', 'direct'),
  ('Lakshmikumaran & Sridharan', 'https://www.lakshmisri.com/careers/', 'law_firm', 'direct'),
  ('Singhania & Partners', 'https://singhania.in/careers/', 'law_firm', 'direct'),
  ('Maheshwari & Co.', 'https://www.maheshwariandco.com/careers/', 'law_firm', 'direct'),
  ('Solomon & Co.', 'https://solomonco.in/careers/', 'law_firm', 'direct'),
  ('S&R Associates', 'https://www.snrlaw.in/careers/', 'law_firm', 'direct'),
  ('Anand and Anand', 'https://www.anandandanand.com/careers', 'law_firm', 'direct'),
  ('Luthra and Luthra Law Offices', 'https://www.luthra.com/careers/', 'law_firm', 'direct'),
  ('DSK Legal', 'https://www.dsklegal.com/careers/', 'law_firm', 'direct'),
  ('Economic Laws Practice (ELP)', 'https://elplaw.in/careers/', 'law_firm', 'direct'),
  ('Talwar Thakore & Associates', 'https://www.tta.in/careers', 'law_firm', 'direct'),
  ('Wadia Ghandy & Co.', 'https://www.wadiaghandy.com/careers/', 'law_firm', 'direct'),
  ('Kochhar & Co.', 'https://www.kochhar.com/careers/', 'law_firm', 'direct'),
  ('NLSIU Bangalore Careers', 'https://www.nls.ac.in/', 'court', 'direct'),
  ('NALSAR Hyderabad', 'https://www.nalsar.ac.in/', 'court', 'direct'),
  ('National Law University Delhi', 'https://www.nludelhi.ac.in/', 'court', 'direct'),
  ('WBNUJS Kolkata', 'https://www.nujs.edu/', 'court', 'direct'),
  ('Gujarat National Law University', 'https://www.gnlu.ac.in/', 'court', 'direct'),
  ('National Centre for Law and Administration (LBSNAA)', 'https://ncla.lbsnaa.gov.in/', 'court', 'direct'),
  ('Vidhi Centre for Legal Policy', 'https://vidhilegalpolicy.in/careers/', 'ngo', 'direct'),
  ('Centre for Civil Society', 'https://ccs.in/internship-programs', 'ngo', 'direct'),
  ('PRS Legislative Research', 'https://prsindia.org/jobs', 'ngo', 'direct'),
  ('Human Rights Law Network', 'https://hrln.org/', 'ngo', 'direct'),
  ('Commonwealth Human Rights Initiative', 'https://www.humanrightsinitiative.org/', 'ngo', 'direct'),
  ('Centre for Policy Research', 'https://cprindia.org/careers/', 'ngo', 'direct'),
  ('Amnesty International India', 'https://amnesty.org.in/get-involved/', 'ngo', 'direct'),
  ('India Justice Report / DAKSH', 'https://www.dakshindia.org/', 'ngo', 'direct'),
  ('SCC Online (Careers)', 'https://www.scconline.com/', 'edtech', 'direct'),
  ('Manupatra', 'https://www.manupatra.com/', 'edtech', 'direct'),
  ('iPleaders (LawSikho)', 'https://www.ipleaders.in/', 'edtech', 'direct'),
  ('Legal Bites', 'https://www.legalbites.in/', 'edtech', 'direct'),
  ('Law Times Journal', 'https://lawtimesjournal.in/', 'edtech', 'direct'),
  ('Latest Laws', 'https://www.latestlaws.com/', 'edtech', 'direct'),
  ('SCC Times Blog', 'https://www.scconline.com/blog/category/notifications/', 'edtech', 'direct'),
  ('Cyril Amarchand Blogs Careers', 'https://corporate.cyrilamarchandblogs.com/careers/', 'law_firm', 'direct'),
  ('Argus Partners', 'https://www.argus-partners.com/careers/', 'law_firm', 'direct'),
  ('Link Legal', 'https://www.linklegal.in/careers', 'law_firm', 'direct'),
  ('HSA Advocates', 'https://www.hsalegal.com/careers/', 'law_firm', 'direct'),
  ('ALMT Legal', 'https://almtlegal.com/careers/', 'law_firm', 'direct'),
  ('Clasis Law', 'https://www.clasislaw.com/careers/', 'law_firm', 'direct'),
  ('Legal 500 India Rankings', 'https://www.legal500.com/c/india/', 'portal', 'direct'),
  ('Chambers and Partners India', 'https://chambers.com/legal-guide/india', 'portal', 'direct'),
  ('Legal Desire', 'https://legaldesire.com/category/opportunities/', 'portal', 'direct'),
  ('Symbiosis Law School Placement Cell', 'https://www.symlaw.ac.in/placement/', 'court', 'direct'),
  ('ILS Law College Placement Cell', 'https://www.ilslaw.edu/', 'court', 'direct'),
  ('Supreme Court of India', 'https://www.sci.gov.in', 'court', 'direct'),
  ('Allahabad High Court', 'https://www.allahabadhighcourt.in', 'court', 'direct'),
  ('Andhra Pradesh High Court', 'https://aphc.gov.in', 'court', 'direct'),
  ('Bombay High Court', 'https://bombayhighcourt.nic.in', 'court', 'direct'),
  ('Calcutta High Court', 'https://www.calcuttahighcourt.gov.in', 'court', 'direct'),
  ('Chhattisgarh High Court', 'https://highcourt.cg.gov.in', 'court', 'direct'),
  ('Delhi High Court', 'https://www.delhihighcourt.nic.in', 'court', 'direct'),
  ('Gauhati High Court', 'https://ghconline.gov.in', 'court', 'direct'),
  ('Gujarat High Court', 'https://gujarathighcourt.nic.in', 'court', 'direct'),
  ('Himachal Pradesh High Court', 'https://hphighcourt.nic.in', 'court', 'direct'),
  ('Jammu & Kashmir and Ladakh High Court', 'https://jkhighcourt.nic.in', 'court', 'direct'),
  ('Jharkhand High Court', 'https://jharkhandhighcourt.nic.in', 'court', 'direct'),
  ('Karnataka High Court', 'https://karnatakajudiciary.kar.nic.in', 'court', 'direct'),
  ('Kerala High Court', 'https://highcourtofkerala.nic.in', 'court', 'direct'),
  ('Madhya Pradesh High Court', 'https://mphc.gov.in', 'court', 'direct'),
  ('Madras High Court', 'https://www.hcmadras.tn.nic.in', 'court', 'direct'),
  ('Manipur High Court', 'https://hcmimphal.nic.in', 'court', 'direct'),
  ('Meghalaya High Court', 'https://meghalayahighcourt.nic.in', 'court', 'direct'),
  ('Orissa High Court', 'https://orissahighcourt.nic.in', 'court', 'direct'),
  ('Patna High Court', 'https://patnahighcourt.gov.in', 'court', 'direct'),
  ('Punjab & Haryana High Court', 'https://phhc.gov.in', 'court', 'direct'),
  ('Rajasthan High Court', 'https://hcraj.nic.in', 'court', 'direct'),
  ('Sikkim High Court', 'https://hcs.gov.in', 'court', 'direct'),
  ('Telangana High Court', 'https://tshc.gov.in', 'court', 'direct'),
  ('Tripura High Court', 'https://thc.nic.in', 'court', 'direct'),
  ('Uttarakhand High Court', 'https://highcourtofuttarakhand.gov.in', 'court', 'direct'),
  ('Andhra Pradesh District Court - Anantapur', 'https://districts.ecourts.gov.in/anantapur', 'court', 'direct'),
  ('Andhra Pradesh District Court - Chittoor', 'https://districts.ecourts.gov.in/chittoor', 'court', 'direct'),
  ('Andhra Pradesh District Court - East Godavari', 'https://districts.ecourts.gov.in/east-godavari', 'court', 'direct'),
  ('Andhra Pradesh District Court - Guntur', 'https://districts.ecourts.gov.in/guntur', 'court', 'direct'),
  ('Andhra Pradesh District Court - Krishna', 'https://districts.ecourts.gov.in/krishna', 'court', 'direct'),
  ('Andhra Pradesh District Court - Kurnool', 'https://districts.ecourts.gov.in/kurnool', 'court', 'direct'),
  ('Andhra Pradesh District Court - Nellore', 'https://districts.ecourts.gov.in/nellore', 'court', 'direct'),
  ('Andhra Pradesh District Court - Prakasam', 'https://districts.ecourts.gov.in/prakasam', 'court', 'direct'),
  ('Andhra Pradesh District Court - Srikakulamm', 'https://districts.ecourts.gov.in/srikakulamm', 'court', 'direct'),
  ('Andhra Pradesh District Court - Visa', 'https://districts.ecourts.gov.in/visa', 'court', 'direct'),
  ('Andhra Pradesh District Court - Vizikhapatnamanagaram', 'https://districts.ecourts.gov.in/vizikhapatnamanagaram', 'court', 'direct'),
  ('Andhra Pradesh District Court - West Godavari', 'https://districts.ecourts.gov.in/west-godavari', 'court', 'direct'),
  ('Andhra Pradesh District Court - Kadapa', 'https://districts.ecourts.gov.in/kadapa', 'court', 'direct'),
  ('Arunachal Pradesh District Court - Papumpare', 'https://districts.ecourts.gov.in/papumpare', 'court', 'direct'),
  ('Arunachal Pradesh District Court - Wepumparestkameng', 'https://districts.ecourts.gov.in/wepumparestkameng', 'court', 'direct'),
  ('Assam District Court - Baksa', 'https://districts.ecourts.gov.in/baksa', 'court', 'direct'),
  ('Assam District Court - Barpeta', 'https://districts.ecourts.gov.in/barpeta', 'court', 'direct'),
  ('Assam District Court - Bongaigaon', 'https://districts.ecourts.gov.in/bongaigaon', 'court', 'direct'),
  ('Assam District Court - Cachar', 'https://districts.ecourts.gov.in/cachar', 'court', 'direct'),
  ('Assam District Court - Darrang', 'https://districts.ecourts.gov.in/darrang', 'court', 'direct'),
  ('Assam District Court - Dhemaji', 'https://districts.ecourts.gov.in/dhemaji', 'court', 'direct'),
  ('Assam District Court - Dhubri', 'https://districts.ecourts.gov.in/dhubri', 'court', 'direct'),
  ('Assam District Court - Dibrugarh', 'https://districts.ecourts.gov.in/dibrugarh', 'court', 'direct'),
  ('Assam District Court - Goalpara', 'https://districts.ecourts.gov.in/goalpara', 'court', 'direct'),
  ('Assam District Court - Golaghat', 'https://districts.ecourts.gov.in/golaghat', 'court', 'direct'),
  ('Assam District Court - Hailakandi', 'https://districts.ecourts.gov.in/hailakandi', 'court', 'direct'),
  ('Assam District Court - Jorhat', 'https://districts.ecourts.gov.in/jorhat', 'court', 'direct'),
  ('Assam District Court - Kamrup', 'https://districts.ecourts.gov.in/kamrup', 'court', 'direct'),
  ('Assam District Court - Kamrupmetropolitan', 'https://districts.ecourts.gov.in/kamrupmetropolitan', 'court', 'direct'),
  ('Assam District Court - Karbianglong', 'https://districts.ecourts.gov.in/karbianglong', 'court', 'direct'),
  ('Assam District Court - Karimganj', 'https://districts.ecourts.gov.in/karimganj', 'court', 'direct'),
  ('Assam District Court - Kokrajhar', 'https://districts.ecourts.gov.in/kokrajhar', 'court', 'direct'),
  ('Assam District Court - Lakhimpur', 'https://districts.ecourts.gov.in/lakhimpur', 'court', 'direct'),
  ('Assam District Court - Morigaon', 'https://districts.ecourts.gov.in/morigaon', 'court', 'direct'),
  ('Assam District Court - Nagaon', 'https://districts.ecourts.gov.in/nagaon', 'court', 'direct'),
  ('Assam District Court - Nalbari', 'https://districts.ecourts.gov.in/nalbari', 'court', 'direct'),
  ('Assam District Court - Sivasagar', 'https://districts.ecourts.gov.in/sivasagar', 'court', 'direct'),
  ('Assam District Court - Sonitpur', 'https://districts.ecourts.gov.in/sonitpur', 'court', 'direct'),
  ('Assam District Court - Tinsukia', 'https://districts.ecourts.gov.in/tinsukia', 'court', 'direct'),
  ('Assam District Court - Udalguri', 'https://districts.ecourts.gov.in/udalguri', 'court', 'direct'),
  ('Assam District Court - Dimahasao', 'https://districts.ecourts.gov.in/dimahasao', 'court', 'direct'),
  ('Assam District Court - Chirang', 'https://districts.ecourts.gov.in/chirang', 'court', 'direct'),
  ('Bihar District Court - Araria', 'https://districts.ecourts.gov.in/araria', 'court', 'direct'),
  ('Bihar District Court - Arwal', 'https://districts.ecourts.gov.in/arwal', 'court', 'direct'),
  ('Bihar District Court - Aurangabadbr', 'https://districts.ecourts.gov.in/aurangabadbr', 'court', 'direct'),
  ('Bihar District Court - Banka', 'https://districts.ecourts.gov.in/banka', 'court', 'direct'),
  ('Bihar District Court - Begusarai', 'https://districts.ecourts.gov.in/begusarai', 'court', 'direct'),
  ('Bihar District Court - Bhagalpur', 'https://districts.ecourts.gov.in/bhagalpur', 'court', 'direct'),
  ('Bihar District Court - Bhojpur', 'https://districts.ecourts.gov.in/bhojpur', 'court', 'direct'),
  ('Bihar District Court - Buxar', 'https://districts.ecourts.gov.in/buxar', 'court', 'direct'),
  ('Bihar District Court - Darbhanga', 'https://districts.ecourts.gov.in/darbhanga', 'court', 'direct'),
  ('Bihar District Court - Eastchamparan', 'https://districts.ecourts.gov.in/eastchamparan', 'court', 'direct'),
  ('Bihar District Court - Gaya', 'https://districts.ecourts.gov.in/gaya', 'court', 'direct'),
  ('Bihar District Court - Gopalganj', 'https://districts.ecourts.gov.in/gopalganj', 'court', 'direct'),
  ('Bihar District Court - Jamui', 'https://districts.ecourts.gov.in/jamui', 'court', 'direct'),
  ('Bihar District Court - Jehanabad', 'https://districts.ecourts.gov.in/jehanabad', 'court', 'direct'),
  ('Bihar District Court - Kaimur', 'https://districts.ecourts.gov.in/kaimur', 'court', 'direct'),
  ('Bihar District Court - Katihar', 'https://districts.ecourts.gov.in/katihar', 'court', 'direct'),
  ('Bihar District Court - Khagaria', 'https://districts.ecourts.gov.in/khagaria', 'court', 'direct'),
  ('Bihar District Court - Kishanganj', 'https://districts.ecourts.gov.in/kishanganj', 'court', 'direct'),
  ('Bihar District Court - Lakhisarai', 'https://districts.ecourts.gov.in/lakhisarai', 'court', 'direct'),
  ('Bihar District Court - Madhepura', 'https://districts.ecourts.gov.in/madhepura', 'court', 'direct'),
  ('Bihar District Court - Madhubani', 'https://districts.ecourts.gov.in/madhubani', 'court', 'direct'),
  ('Bihar District Court - Munger', 'https://districts.ecourts.gov.in/munger', 'court', 'direct'),
  ('Bihar District Court - Muzaffarpur', 'https://districts.ecourts.gov.in/muzaffarpur', 'court', 'direct'),
  ('Bihar District Court - Nalanda', 'https://districts.ecourts.gov.in/nalanda', 'court', 'direct'),
  ('Bihar District Court - Nawada', 'https://districts.ecourts.gov.in/nawada', 'court', 'direct'),
  ('Bihar District Court - Patna', 'https://districts.ecourts.gov.in/patna', 'court', 'direct'),
  ('Bihar District Court - Purnia', 'https://districts.ecourts.gov.in/purnia', 'court', 'direct'),
  ('Bihar District Court - Rohtas', 'https://districts.ecourts.gov.in/rohtas', 'court', 'direct'),
  ('Bihar District Court - Saharsa', 'https://districts.ecourts.gov.in/saharsa', 'court', 'direct'),
  ('Bihar District Court - Samastipur', 'https://districts.ecourts.gov.in/samastipur', 'court', 'direct'),
  ('Bihar District Court - Saran', 'https://districts.ecourts.gov.in/saran', 'court', 'direct'),
  ('Bihar District Court - Sheikhpura', 'https://districts.ecourts.gov.in/sheikhpura', 'court', 'direct'),
  ('Bihar District Court - Sheohar', 'https://districts.ecourts.gov.in/sheohar', 'court', 'direct'),
  ('Bihar District Court - Sitamarhi', 'https://districts.ecourts.gov.in/sitamarhi', 'court', 'direct'),
  ('Bihar District Court - Siwan', 'https://districts.ecourts.gov.in/siwan', 'court', 'direct'),
  ('Bihar District Court - Supaul', 'https://districts.ecourts.gov.in/supaul', 'court', 'direct'),
  ('Bihar District Court - Vaishali', 'https://districts.ecourts.gov.in/vaishali', 'court', 'direct'),
  ('Bihar District Court - Westchamparan', 'https://districts.ecourts.gov.in/westchamparan', 'court', 'direct'),
  ('Chhattisgarh District Court - Balod', 'https://districts.ecourts.gov.in/balod', 'court', 'direct'),
  ('Chhattisgarh District Court - Balodabazar', 'https://districts.ecourts.gov.in/balodabazar', 'court', 'direct'),
  ('Chhattisgarh District Court - Balrampurcg', 'https://districts.ecourts.gov.in/balrampurcg', 'court', 'direct'),
  ('Chhattisgarh District Court - Bastar', 'https://districts.ecourts.gov.in/bastar', 'court', 'direct'),
  ('Chhattisgarh District Court - Bemetara', 'https://districts.ecourts.gov.in/bemetara', 'court', 'direct'),
  ('Chhattisgarh District Court - Bijapurcg', 'https://districts.ecourts.gov.in/bijapurcg', 'court', 'direct'),
  ('Chhattisgarh District Court - Bilaspurcg', 'https://districts.ecourts.gov.in/bilaspurcg', 'court', 'direct'),
  ('Chhattisgarh District Court - Dantewada', 'https://districts.ecourts.gov.in/dantewada', 'court', 'direct'),
  ('Chhattisgarh District Court - Dhamtari', 'https://districts.ecourts.gov.in/dhamtari', 'court', 'direct'),
  ('Chhattisgarh District Court - Durg', 'https://districts.ecourts.gov.in/durg', 'court', 'direct'),
  ('Chhattisgarh District Court - Gariaband', 'https://districts.ecourts.gov.in/gariaband', 'court', 'direct'),
  ('Chhattisgarh District Court - Janjgirchampa', 'https://districts.ecourts.gov.in/janjgirchampa', 'court', 'direct'),
  ('Chhattisgarh District Court - Jashpur', 'https://districts.ecourts.gov.in/jashpur', 'court', 'direct'),
  ('Chhattisgarh District Court - Kanker', 'https://districts.ecourts.gov.in/kanker', 'court', 'direct'),
  ('Chhattisgarh District Court - Kabirdham', 'https://districts.ecourts.gov.in/kabirdham', 'court', 'direct'),
  ('Chhattisgarh District Court - Kondagaon', 'https://districts.ecourts.gov.in/kondagaon', 'court', 'direct'),
  ('Chhattisgarh District Court - Korba', 'https://districts.ecourts.gov.in/korba', 'court', 'direct'),
  ('Chhattisgarh District Court - Koriya', 'https://districts.ecourts.gov.in/koriya', 'court', 'direct'),
  ('Chhattisgarh District Court - Mahasamund', 'https://districts.ecourts.gov.in/mahasamund', 'court', 'direct'),
  ('Chhattisgarh District Court - Mungeli', 'https://districts.ecourts.gov.in/mungeli', 'court', 'direct'),
  ('Chhattisgarh District Court - Narayanpur', 'https://districts.ecourts.gov.in/narayanpur', 'court', 'direct'),
  ('Chhattisgarh District Court - Raigarhcg', 'https://districts.ecourts.gov.in/raigarhcg', 'court', 'direct'),
  ('Chhattisgarh District Court - Raipur', 'https://districts.ecourts.gov.in/raipur', 'court', 'direct'),
  ('Chhattisgarh District Court - Rajnandgaon', 'https://districts.ecourts.gov.in/rajnandgaon', 'court', 'direct'),
  ('Chhattisgarh District Court - Sukma', 'https://districts.ecourts.gov.in/sukma', 'court', 'direct'),
  ('Chhattisgarh District Court - Surajpur', 'https://districts.ecourts.gov.in/surajpur', 'court', 'direct'),
  ('Chhattisgarh District Court - Surgujai', 'https://districts.ecourts.gov.in/surgujai', 'court', 'direct'),
  ('Chhattisgarh District Court - Gpmarwahi', 'https://districts.ecourts.gov.in/gpmarwahi', 'court', 'direct'),
  ('Goa District Court - Northgoa', 'https://districts.ecourts.gov.in/northgoa', 'court', 'direct'),
  ('Goa District Court - Southgoa', 'https://districts.ecourts.gov.in/southgoa', 'court', 'direct'),
  ('Gujarat District Court - Ahmedabad', 'https://districts.ecourts.gov.in/ahmedabad', 'court', 'direct'),
  ('Gujarat District Court - Amreli', 'https://districts.ecourts.gov.in/amreli', 'court', 'direct'),
  ('Gujarat District Court - Anand', 'https://districts.ecourts.gov.in/anand', 'court', 'direct'),
  ('Gujarat District Court - Aravalli', 'https://districts.ecourts.gov.in/aravalli', 'court', 'direct'),
  ('Gujarat District Court - Banaskantha', 'https://districts.ecourts.gov.in/banaskantha', 'court', 'direct'),
  ('Gujarat District Court - Bharuch', 'https://districts.ecourts.gov.in/bharuch', 'court', 'direct'),
  ('Gujarat District Court - Bhavnagar', 'https://districts.ecourts.gov.in/bhavnagar', 'court', 'direct'),
  ('Gujarat District Court - Botad', 'https://districts.ecourts.gov.in/botad', 'court', 'direct'),
  ('Gujarat District Court - Chhotaudaipur', 'https://districts.ecourts.gov.in/chhotaudaipur', 'court', 'direct'),
  ('Gujarat District Court - Dahod', 'https://districts.ecourts.gov.in/dahod', 'court', 'direct'),
  ('Gujarat District Court - Dang', 'https://districts.ecourts.gov.in/dang', 'court', 'direct'),
  ('Gujarat District Court - Devbhoomidwarka', 'https://districts.ecourts.gov.in/devbhoomidwarka', 'court', 'direct'),
  ('Gujarat District Court - Gandhinagar', 'https://districts.ecourts.gov.in/gandhinagar', 'court', 'direct'),
  ('Gujarat District Court - Girsomnath', 'https://districts.ecourts.gov.in/girsomnath', 'court', 'direct'),
  ('Gujarat District Court - Jamnagar', 'https://districts.ecourts.gov.in/jamnagar', 'court', 'direct'),
  ('Gujarat District Court - Junagadh', 'https://districts.ecourts.gov.in/junagadh', 'court', 'direct'),
  ('Gujarat District Court - Kutch', 'https://districts.ecourts.gov.in/kutch', 'court', 'direct'),
  ('Gujarat District Court - Kheda', 'https://districts.ecourts.gov.in/kheda', 'court', 'direct'),
  ('Gujarat District Court - Mahisagar', 'https://districts.ecourts.gov.in/mahisagar', 'court', 'direct'),
  ('Gujarat District Court - Mehsana', 'https://districts.ecourts.gov.in/mehsana', 'court', 'direct'),
  ('Gujarat District Court - Morbi', 'https://districts.ecourts.gov.in/morbi', 'court', 'direct'),
  ('Gujarat District Court - Narmada', 'https://districts.ecourts.gov.in/narmada', 'court', 'direct'),
  ('Gujarat District Court - Navsari', 'https://districts.ecourts.gov.in/navsari', 'court', 'direct'),
  ('Gujarat District Court - Panchmahal', 'https://districts.ecourts.gov.in/panchmahal', 'court', 'direct'),
  ('Gujarat District Court - Patan', 'https://districts.ecourts.gov.in/patan', 'court', 'direct'),
  ('Gujarat District Court - Porbandar', 'https://districts.ecourts.gov.in/porbandar', 'court', 'direct'),
  ('Gujarat District Court - Rajkot', 'https://districts.ecourts.gov.in/rajkot', 'court', 'direct'),
  ('Gujarat District Court - Sabarkantha', 'https://districts.ecourts.gov.in/sabarkantha', 'court', 'direct'),
  ('Gujarat District Court - Surat', 'https://districts.ecourts.gov.in/surat', 'court', 'direct'),
  ('Gujarat District Court - Surendranagar', 'https://districts.ecourts.gov.in/surendranagar', 'court', 'direct'),
  ('Gujarat District Court - Tapi', 'https://districts.ecourts.gov.in/tapi', 'court', 'direct'),
  ('Gujarat District Court - Vadodara', 'https://districts.ecourts.gov.in/vadodara', 'court', 'direct'),
  ('Gujarat District Court - Valsad', 'https://districts.ecourts.gov.in/valsad', 'court', 'direct'),
  ('Haryana District Court - Ambala', 'https://districts.ecourts.gov.in/ambala', 'court', 'direct'),
  ('Haryana District Court - Bhiwani', 'https://districts.ecourts.gov.in/bhiwani', 'court', 'direct'),
  ('Haryana District Court - Charkhidadri', 'https://districts.ecourts.gov.in/charkhidadri', 'court', 'direct'),
  ('Haryana District Court - Faridabad', 'https://districts.ecourts.gov.in/faridabad', 'court', 'direct'),
  ('Haryana District Court - Fatehabad', 'https://districts.ecourts.gov.in/fatehabad', 'court', 'direct'),
  ('Haryana District Court - Gurugram', 'https://districts.ecourts.gov.in/gurugram', 'court', 'direct'),
  ('Haryana District Court - Hisar', 'https://districts.ecourts.gov.in/hisar', 'court', 'direct'),
  ('Haryana District Court - Jhajjar', 'https://districts.ecourts.gov.in/jhajjar', 'court', 'direct'),
  ('Haryana District Court - Jind', 'https://districts.ecourts.gov.in/jind', 'court', 'direct'),
  ('Haryana District Court - Kaithal', 'https://districts.ecourts.gov.in/kaithal', 'court', 'direct'),
  ('Haryana District Court - Karnal', 'https://districts.ecourts.gov.in/karnal', 'court', 'direct'),
  ('Haryana District Court - Kurukshetrah', 'https://districts.ecourts.gov.in/kurukshetrah', 'court', 'direct'),
  ('Haryana District Court - Mahendragarh', 'https://districts.ecourts.gov.in/mahendragarh', 'court', 'direct'),
  ('Haryana District Court - Nuh', 'https://districts.ecourts.gov.in/nuh', 'court', 'direct'),
  ('Haryana District Court - Palendragarhwal', 'https://districts.ecourts.gov.in/palendragarhwal', 'court', 'direct'),
  ('Haryana District Court - Panchkula', 'https://districts.ecourts.gov.in/panchkula', 'court', 'direct'),
  ('Haryana District Court - Panipat', 'https://districts.ecourts.gov.in/panipat', 'court', 'direct'),
  ('Haryana District Court - Rewari', 'https://districts.ecourts.gov.in/rewari', 'court', 'direct'),
  ('Haryana District Court - Rohtak', 'https://districts.ecourts.gov.in/rohtak', 'court', 'direct'),
  ('Haryana District Court - Sirsa', 'https://districts.ecourts.gov.in/sirsa', 'court', 'direct'),
  ('Haryana District Court - Sonipat', 'https://districts.ecourts.gov.in/sonipat', 'court', 'direct'),
  ('Haryana District Court - Yamunanagar', 'https://districts.ecourts.gov.in/yamunanagar', 'court', 'direct'),
  ('Himachal Pradesh District Court - Bilaspurhp', 'https://districts.ecourts.gov.in/bilaspurhp', 'court', 'direct'),
  ('Himachal Pradesh District Court - Chamba', 'https://districts.ecourts.gov.in/chamba', 'court', 'direct'),
  ('Himachal Pradesh District Court - Hamirpurhp', 'https://districts.ecourts.gov.in/hamirpurhp', 'court', 'direct'),
  ('Himachal Pradesh District Court - Kangra', 'https://districts.ecourts.gov.in/kangra', 'court', 'direct'),
  ('Himachal Pradesh District Court - Kinnaur', 'https://districts.ecourts.gov.in/kinnaur', 'court', 'direct'),
  ('Himachal Pradesh District Court - Kullu', 'https://districts.ecourts.gov.in/kullu', 'court', 'direct'),
  ('Himachal Pradesh District Court - Lahaulspiti', 'https://districts.ecourts.gov.in/lahaulspiti', 'court', 'direct'),
  ('Himachal Pradesh District Court - Mandi', 'https://districts.ecourts.gov.in/mandi', 'court', 'direct'),
  ('Himachal Pradesh District Court - Shimla', 'https://districts.ecourts.gov.in/shimla', 'court', 'direct'),
  ('Himachal Pradesh District Court - Sirmaur', 'https://districts.ecourts.gov.in/sirmaur', 'court', 'direct'),
  ('Himachal Pradesh District Court - Solan', 'https://districts.ecourts.gov.in/solan', 'court', 'direct'),
  ('Himachal Pradesh District Court - Una', 'https://districts.ecourts.gov.in/una', 'court', 'direct'),
  ('Jharkhand District Court - Bokaro', 'https://districts.ecourts.gov.in/bokaro', 'court', 'direct'),
  ('Jharkhand District Court - Chatra', 'https://districts.ecourts.gov.in/chatra', 'court', 'direct'),
  ('Jharkhand District Court - Deoghar', 'https://districts.ecourts.gov.in/deoghar', 'court', 'direct'),
  ('Jharkhand District Court - Dhanbad', 'https://districts.ecourts.gov.in/dhanbad', 'court', 'direct'),
  ('Jharkhand District Court - Dumka', 'https://districts.ecourts.gov.in/dumka', 'court', 'direct'),
  ('Jharkhand District Court - Eastsinghbhum', 'https://districts.ecourts.gov.in/eastsinghbhum', 'court', 'direct'),
  ('Jharkhand District Court - Garhwa', 'https://districts.ecourts.gov.in/garhwa', 'court', 'direct'),
  ('Jharkhand District Court - Giridih', 'https://districts.ecourts.gov.in/giridih', 'court', 'direct'),
  ('Jharkhand District Court - Godda', 'https://districts.ecourts.gov.in/godda', 'court', 'direct'),
  ('Jharkhand District Court - Gumla', 'https://districts.ecourts.gov.in/gumla', 'court', 'direct'),
  ('Jharkhand District Court - Hazaribag', 'https://districts.ecourts.gov.in/hazaribag', 'court', 'direct'),
  ('Jharkhand District Court - Jamtara', 'https://districts.ecourts.gov.in/jamtara', 'court', 'direct'),
  ('Jharkhand District Court - Khunti', 'https://districts.ecourts.gov.in/khunti', 'court', 'direct'),
  ('Jharkhand District Court - Koderma', 'https://districts.ecourts.gov.in/koderma', 'court', 'direct'),
  ('Jharkhand District Court - Latehar', 'https://districts.ecourts.gov.in/latehar', 'court', 'direct'),
  ('Jharkhand District Court - Lohardaga', 'https://districts.ecourts.gov.in/lohardaga', 'court', 'direct'),
  ('Jharkhand District Court - Pakur', 'https://districts.ecourts.gov.in/pakur', 'court', 'direct'),
  ('Jharkhand District Court - Palamu', 'https://districts.ecourts.gov.in/palamu', 'court', 'direct'),
  ('Jharkhand District Court - Ramgarh', 'https://districts.ecourts.gov.in/ramgarh', 'court', 'direct'),
  ('Jharkhand District Court - Ranchi', 'https://districts.ecourts.gov.in/ranchi', 'court', 'direct'),
  ('Jharkhand District Court - Sahebganjn', 'https://districts.ecourts.gov.in/sahebganjn', 'court', 'direct'),
  ('Jharkhand District Court - Seraikel', 'https://districts.ecourts.gov.in/seraikel', 'court', 'direct'),
  ('Jharkhand District Court - Simdega', 'https://districts.ecourts.gov.in/simdega', 'court', 'direct'),
  ('Jharkhand District Court - Westsingakharsawanhbhum', 'https://districts.ecourts.gov.in/westsingakharsawanhbhum', 'court', 'direct'),
  ('Karnataka District Court - Bagalkot', 'https://districts.ecourts.gov.in/bagalkot', 'court', 'direct'),
  ('Karnataka District Court - Bengaluruurban', 'https://districts.ecourts.gov.in/bengaluruurban', 'court', 'direct'),
  ('Karnataka District Court - Bengalururural', 'https://districts.ecourts.gov.in/bengalururural', 'court', 'direct'),
  ('Karnataka District Court - Belagavi', 'https://districts.ecourts.gov.in/belagavi', 'court', 'direct'),
  ('Karnataka District Court - Ballari', 'https://districts.ecourts.gov.in/ballari', 'court', 'direct'),
  ('Karnataka District Court - Bidar', 'https://districts.ecourts.gov.in/bidar', 'court', 'direct'),
  ('Karnataka District Court - Chamarajanagar', 'https://districts.ecourts.gov.in/chamarajanagar', 'court', 'direct'),
  ('Karnataka District Court - Chikkaballapur', 'https://districts.ecourts.gov.in/chikkaballapur', 'court', 'direct'),
  ('Karnataka District Court - Chikkamagaluru', 'https://districts.ecourts.gov.in/chikkamagaluru', 'court', 'direct'),
  ('Karnataka District Court - Chitradurga', 'https://districts.ecourts.gov.in/chitradurga', 'court', 'direct'),
  ('Karnataka District Court - Dakshi', 'https://districts.ecourts.gov.in/dakshi', 'court', 'direct'),
  ('Karnataka District Court - Davananakannadagere', 'https://districts.ecourts.gov.in/davananakannadagere', 'court', 'direct'),
  ('Karnataka District Court - Dharwad', 'https://districts.ecourts.gov.in/dharwad', 'court', 'direct'),
  ('Karnataka District Court - Gadag', 'https://districts.ecourts.gov.in/gadag', 'court', 'direct'),
  ('Karnataka District Court - Hassan', 'https://districts.ecourts.gov.in/hassan', 'court', 'direct'),
  ('Karnataka District Court - Haveri', 'https://districts.ecourts.gov.in/haveri', 'court', 'direct'),
  ('Karnataka District Court - Kalaburagi', 'https://districts.ecourts.gov.in/kalaburagi', 'court', 'direct'),
  ('Karnataka District Court - Kodagu', 'https://districts.ecourts.gov.in/kodagu', 'court', 'direct'),
  ('Karnataka District Court - Kolar', 'https://districts.ecourts.gov.in/kolar', 'court', 'direct'),
  ('Karnataka District Court - Koppal', 'https://districts.ecourts.gov.in/koppal', 'court', 'direct'),
  ('Karnataka District Court - Mandya', 'https://districts.ecourts.gov.in/mandya', 'court', 'direct'),
  ('Karnataka District Court - Mysuru', 'https://districts.ecourts.gov.in/mysuru', 'court', 'direct'),
  ('Karnataka District Court - Raichur', 'https://districts.ecourts.gov.in/raichur', 'court', 'direct'),
  ('Karnataka District Court - Ramanagara', 'https://districts.ecourts.gov.in/ramanagara', 'court', 'direct'),
  ('Karnataka District Court - Shivamogga', 'https://districts.ecourts.gov.in/shivamogga', 'court', 'direct'),
  ('Karnataka District Court - Tumakuru', 'https://districts.ecourts.gov.in/tumakuru', 'court', 'direct'),
  ('Karnataka District Court - Udupi', 'https://districts.ecourts.gov.in/udupi', 'court', 'direct'),
  ('Karnataka District Court - Uttarakannada', 'https://districts.ecourts.gov.in/uttarakannada', 'court', 'direct'),
  ('Karnataka District Court - Vijayapura', 'https://districts.ecourts.gov.in/vijayapura', 'court', 'direct'),
  ('Karnataka District Court - Yadgir', 'https://districts.ecourts.gov.in/yadgir', 'court', 'direct'),
  ('Karnataka District Court - Vijayanagar', 'https://districts.ecourts.gov.in/vijayanagar', 'court', 'direct'),
  ('Kerala District Court - Thiruvan', 'https://districts.ecourts.gov.in/thiruvan', 'court', 'direct'),
  ('Kerala District Court - Kollam', 'https://districts.ecourts.gov.in/kollam', 'court', 'direct'),
  ('Kerala District Court - Pathanamanthapuramthitta', 'https://districts.ecourts.gov.in/pathanamanthapuramthitta', 'court', 'direct'),
  ('Kerala District Court - Alappuzha', 'https://districts.ecourts.gov.in/alappuzha', 'court', 'direct'),
  ('Kerala District Court - Kottayam', 'https://districts.ecourts.gov.in/kottayam', 'court', 'direct'),
  ('Kerala District Court - Idukki', 'https://districts.ecourts.gov.in/idukki', 'court', 'direct'),
  ('Kerala District Court - Ernakulam', 'https://districts.ecourts.gov.in/ernakulam', 'court', 'direct'),
  ('Kerala District Court - Thrissur', 'https://districts.ecourts.gov.in/thrissur', 'court', 'direct'),
  ('Kerala District Court - Palakkad', 'https://districts.ecourts.gov.in/palakkad', 'court', 'direct'),
  ('Kerala District Court - Malappuram', 'https://districts.ecourts.gov.in/malappuram', 'court', 'direct'),
  ('Kerala District Court - Kozhikode', 'https://districts.ecourts.gov.in/kozhikode', 'court', 'direct'),
  ('Kerala District Court - Wayanad', 'https://districts.ecourts.gov.in/wayanad', 'court', 'direct'),
  ('Kerala District Court - Kannur', 'https://districts.ecourts.gov.in/kannur', 'court', 'direct'),
  ('Kerala District Court - Kasaragod', 'https://districts.ecourts.gov.in/kasaragod', 'court', 'direct'),
  ('Madhya Pradesh District Court - Agarmalwa', 'https://districts.ecourts.gov.in/agarmalwa', 'court', 'direct'),
  ('Madhya Pradesh District Court - Alirajpur', 'https://districts.ecourts.gov.in/alirajpur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Anuppur', 'https://districts.ecourts.gov.in/anuppur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Ashoknagar', 'https://districts.ecourts.gov.in/ashoknagar', 'court', 'direct'),
  ('Madhya Pradesh District Court - Balaghat', 'https://districts.ecourts.gov.in/balaghat', 'court', 'direct'),
  ('Madhya Pradesh District Court - Barwani', 'https://districts.ecourts.gov.in/barwani', 'court', 'direct'),
  ('Madhya Pradesh District Court - Betul', 'https://districts.ecourts.gov.in/betul', 'court', 'direct'),
  ('Madhya Pradesh District Court - Bhind', 'https://districts.ecourts.gov.in/bhind', 'court', 'direct'),
  ('Madhya Pradesh District Court - Bhopal', 'https://districts.ecourts.gov.in/bhopal', 'court', 'direct'),
  ('Madhya Pradesh District Court - Burhanpur', 'https://districts.ecourts.gov.in/burhanpur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Chhatarpur', 'https://districts.ecourts.gov.in/chhatarpur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Chhindwara', 'https://districts.ecourts.gov.in/chhindwara', 'court', 'direct'),
  ('Madhya Pradesh District Court - Damoh', 'https://districts.ecourts.gov.in/damoh', 'court', 'direct'),
  ('Madhya Pradesh District Court - Datia', 'https://districts.ecourts.gov.in/datia', 'court', 'direct'),
  ('Madhya Pradesh District Court - Dewas', 'https://districts.ecourts.gov.in/dewas', 'court', 'direct'),
  ('Madhya Pradesh District Court - Dhar', 'https://districts.ecourts.gov.in/dhar', 'court', 'direct'),
  ('Madhya Pradesh District Court - Dindori', 'https://districts.ecourts.gov.in/dindori', 'court', 'direct'),
  ('Madhya Pradesh District Court - Guna', 'https://districts.ecourts.gov.in/guna', 'court', 'direct'),
  ('Madhya Pradesh District Court - Gwalior', 'https://districts.ecourts.gov.in/gwalior', 'court', 'direct'),
  ('Madhya Pradesh District Court - Hardad', 'https://districts.ecourts.gov.in/hardad', 'court', 'direct'),
  ('Madhya Pradesh District Court - Hoshangabad', 'https://districts.ecourts.gov.in/hoshangabad', 'court', 'direct'),
  ('Madhya Pradesh District Court - Inshangabaddore', 'https://districts.ecourts.gov.in/inshangabaddore', 'court', 'direct'),
  ('Madhya Pradesh District Court - Jabalpur', 'https://districts.ecourts.gov.in/jabalpur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Jhabua', 'https://districts.ecourts.gov.in/jhabua', 'court', 'direct'),
  ('Madhya Pradesh District Court - Katni', 'https://districts.ecourts.gov.in/katni', 'court', 'direct'),
  ('Madhya Pradesh District Court - Khandwa', 'https://districts.ecourts.gov.in/khandwa', 'court', 'direct'),
  ('Madhya Pradesh District Court - Khargone', 'https://districts.ecourts.gov.in/khargone', 'court', 'direct'),
  ('Madhya Pradesh District Court - Mandla', 'https://districts.ecourts.gov.in/mandla', 'court', 'direct'),
  ('Madhya Pradesh District Court - Mandsaur', 'https://districts.ecourts.gov.in/mandsaur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Morena', 'https://districts.ecourts.gov.in/morena', 'court', 'direct'),
  ('Madhya Pradesh District Court - Narsinghpur', 'https://districts.ecourts.gov.in/narsinghpur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Neemuch', 'https://districts.ecourts.gov.in/neemuch', 'court', 'direct'),
  ('Madhya Pradesh District Court - Panna', 'https://districts.ecourts.gov.in/panna', 'court', 'direct'),
  ('Madhya Pradesh District Court - Raisen', 'https://districts.ecourts.gov.in/raisen', 'court', 'direct'),
  ('Madhya Pradesh District Court - Rajgarh', 'https://districts.ecourts.gov.in/rajgarh', 'court', 'direct'),
  ('Madhya Pradesh District Court - Ratlam', 'https://districts.ecourts.gov.in/ratlam', 'court', 'direct'),
  ('Madhya Pradesh District Court - Rewa', 'https://districts.ecourts.gov.in/rewa', 'court', 'direct'),
  ('Madhya Pradesh District Court - Sagar', 'https://districts.ecourts.gov.in/sagar', 'court', 'direct'),
  ('Madhya Pradesh District Court - Satna', 'https://districts.ecourts.gov.in/satna', 'court', 'direct'),
  ('Madhya Pradesh District Court - Sehore', 'https://districts.ecourts.gov.in/sehore', 'court', 'direct'),
  ('Madhya Pradesh District Court - Seoni', 'https://districts.ecourts.gov.in/seoni', 'court', 'direct'),
  ('Madhya Pradesh District Court - Shahdol', 'https://districts.ecourts.gov.in/shahdol', 'court', 'direct'),
  ('Madhya Pradesh District Court - Shajapur', 'https://districts.ecourts.gov.in/shajapur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Sheopur', 'https://districts.ecourts.gov.in/sheopur', 'court', 'direct'),
  ('Madhya Pradesh District Court - Shivpuri', 'https://districts.ecourts.gov.in/shivpuri', 'court', 'direct'),
  ('Madhya Pradesh District Court - Sidhi', 'https://districts.ecourts.gov.in/sidhi', 'court', 'direct'),
  ('Madhya Pradesh District Court - Singrauli', 'https://districts.ecourts.gov.in/singrauli', 'court', 'direct'),
  ('Madhya Pradesh District Court - Tikamgarh', 'https://districts.ecourts.gov.in/tikamgarh', 'court', 'direct'),
  ('Madhya Pradesh District Court - Ujjain', 'https://districts.ecourts.gov.in/ujjain', 'court', 'direct'),
  ('Madhya Pradesh District Court - Umaria', 'https://districts.ecourts.gov.in/umaria', 'court', 'direct'),
  ('Madhya Pradesh District Court - Vidisha', 'https://districts.ecourts.gov.in/vidisha', 'court', 'direct'),
  ('Madhya Pradesh District Court - Niwari', 'https://districts.ecourts.gov.in/niwari', 'court', 'direct'),
  ('Maharashtra District Court - Ahmednagar', 'https://districts.ecourts.gov.in/ahmednagar', 'court', 'direct'),
  ('Maharashtra District Court - Akola', 'https://districts.ecourts.gov.in/akola', 'court', 'direct'),
  ('Maharashtra District Court - Amravati', 'https://districts.ecourts.gov.in/amravati', 'court', 'direct'),
  ('Maharashtra District Court - Aurangabadmh', 'https://districts.ecourts.gov.in/aurangabadmh', 'court', 'direct'),
  ('Maharashtra District Court - Beed', 'https://districts.ecourts.gov.in/beed', 'court', 'direct'),
  ('Maharashtra District Court - Bhandara', 'https://districts.ecourts.gov.in/bhandara', 'court', 'direct'),
  ('Maharashtra District Court - Buldhana', 'https://districts.ecourts.gov.in/buldhana', 'court', 'direct'),
  ('Maharashtra District Court - Chandrapur', 'https://districts.ecourts.gov.in/chandrapur', 'court', 'direct'),
  ('Maharashtra District Court - Dhule', 'https://districts.ecourts.gov.in/dhule', 'court', 'direct'),
  ('Maharashtra District Court - Gadchiroli', 'https://districts.ecourts.gov.in/gadchiroli', 'court', 'direct'),
  ('Maharashtra District Court - Gondia', 'https://districts.ecourts.gov.in/gondia', 'court', 'direct'),
  ('Maharashtra District Court - Hingoli', 'https://districts.ecourts.gov.in/hingoli', 'court', 'direct'),
  ('Maharashtra District Court - Jalgaon', 'https://districts.ecourts.gov.in/jalgaon', 'court', 'direct'),
  ('Maharashtra District Court - Jalna', 'https://districts.ecourts.gov.in/jalna', 'court', 'direct'),
  ('Maharashtra District Court - Kolhapur', 'https://districts.ecourts.gov.in/kolhapur', 'court', 'direct'),
  ('Maharashtra District Court - Latur', 'https://districts.ecourts.gov.in/latur', 'court', 'direct'),
  ('Maharashtra District Court - Mumbaicity', 'https://districts.ecourts.gov.in/mumbaicity', 'court', 'direct'),
  ('Maharashtra District Court - Mumbaisuburban', 'https://districts.ecourts.gov.in/mumbaisuburban', 'court', 'direct'),
  ('Maharashtra District Court - Nagpur', 'https://districts.ecourts.gov.in/nagpur', 'court', 'direct'),
  ('Maharashtra District Court - Nanded', 'https://districts.ecourts.gov.in/nanded', 'court', 'direct'),
  ('Maharashtra District Court - Nandurbar', 'https://districts.ecourts.gov.in/nandurbar', 'court', 'direct'),
  ('Maharashtra District Court - Nashik', 'https://districts.ecourts.gov.in/nashik', 'court', 'direct'),
  ('Maharashtra District Court - Osmanabad', 'https://districts.ecourts.gov.in/osmanabad', 'court', 'direct'),
  ('Maharashtra District Court - Palghar', 'https://districts.ecourts.gov.in/palghar', 'court', 'direct'),
  ('Maharashtra District Court - Parbhani', 'https://districts.ecourts.gov.in/parbhani', 'court', 'direct'),
  ('Maharashtra District Court - Pune', 'https://districts.ecourts.gov.in/pune', 'court', 'direct'),
  ('Maharashtra District Court - Raigad', 'https://districts.ecourts.gov.in/raigad', 'court', 'direct'),
  ('Maharashtra District Court - Ratnagiri', 'https://districts.ecourts.gov.in/ratnagiri', 'court', 'direct'),
  ('Maharashtra District Court - Sangli', 'https://districts.ecourts.gov.in/sangli', 'court', 'direct'),
  ('Maharashtra District Court - Satara', 'https://districts.ecourts.gov.in/satara', 'court', 'direct'),
  ('Maharashtra District Court - Sindhudurg', 'https://districts.ecourts.gov.in/sindhudurg', 'court', 'direct'),
  ('Maharashtra District Court - Solapur', 'https://districts.ecourts.gov.in/solapur', 'court', 'direct'),
  ('Maharashtra District Court - Thane', 'https://districts.ecourts.gov.in/thane', 'court', 'direct'),
  ('Maharashtra District Court - Wardha', 'https://districts.ecourts.gov.in/wardha', 'court', 'direct'),
  ('Maharashtra District Court - Washim', 'https://districts.ecourts.gov.in/washim', 'court', 'direct'),
  ('Maharashtra District Court - Yavatmal', 'https://districts.ecourts.gov.in/yavatmal', 'court', 'direct'),
  ('Manipur District Court - Bishnupur', 'https://districts.ecourts.gov.in/bishnupur', 'court', 'direct'),
  ('Manipur District Court - Chandelr', 'https://districts.ecourts.gov.in/chandelr', 'court', 'direct'),
  ('Manipur District Court - Chur', 'https://districts.ecourts.gov.in/chur', 'court', 'direct'),
  ('Manipur District Court - Imphachandpuraleast', 'https://districts.ecourts.gov.in/imphachandpuraleast', 'court', 'direct'),
  ('Manipur District Court - Imphalwest', 'https://districts.ecourts.gov.in/imphalwest', 'court', 'direct'),
  ('Manipur District Court - Senapati', 'https://districts.ecourts.gov.in/senapati', 'court', 'direct'),
  ('Manipur District Court - Tamenglong', 'https://districts.ecourts.gov.in/tamenglong', 'court', 'direct'),
  ('Manipur District Court - Thoubal', 'https://districts.ecourts.gov.in/thoubal', 'court', 'direct'),
  ('Manipur District Court - Ukhrul', 'https://districts.ecourts.gov.in/ukhrul', 'court', 'direct'),
  ('Meghalaya District Court - Eastgarohills', 'https://districts.ecourts.gov.in/eastgarohills', 'court', 'direct'),
  ('Meghalaya District Court - Eastkhasihills', 'https://districts.ecourts.gov.in/eastkhasihills', 'court', 'direct'),
  ('Meghalaya District Court - Jaintiahills', 'https://districts.ecourts.gov.in/jaintiahills', 'court', 'direct'),
  ('Meghalaya District Court - Ribhoi', 'https://districts.ecourts.gov.in/ribhoi', 'court', 'direct'),
  ('Meghalaya District Court - Southgarohills', 'https://districts.ecourts.gov.in/southgarohills', 'court', 'direct'),
  ('Meghalaya District Court - Westgarohills', 'https://districts.ecourts.gov.in/westgarohills', 'court', 'direct'),
  ('Meghalaya District Court - Westkhasihills', 'https://districts.ecourts.gov.in/westkhasihills', 'court', 'direct'),
  ('Mizoram District Court - Aizawl', 'https://districts.ecourts.gov.in/aizawl', 'court', 'direct'),
  ('Mizoram District Court - Champhai', 'https://districts.ecourts.gov.in/champhai', 'court', 'direct'),
  ('Mizoram District Court - Kolasib', 'https://districts.ecourts.gov.in/kolasib', 'court', 'direct'),
  ('Mizoram District Court - Lawngtlai', 'https://districts.ecourts.gov.in/lawngtlai', 'court', 'direct'),
  ('Mizoram District Court - Lunglei', 'https://districts.ecourts.gov.in/lunglei', 'court', 'direct'),
  ('Mizoram District Court - Mamit', 'https://districts.ecourts.gov.in/mamit', 'court', 'direct'),
  ('Mizoram District Court - Saiha', 'https://districts.ecourts.gov.in/saiha', 'court', 'direct'),
  ('Mizoram District Court - Serchhip', 'https://districts.ecourts.gov.in/serchhip', 'court', 'direct'),
  ('Nagaland District Court - Dimapur', 'https://districts.ecourts.gov.in/dimapur', 'court', 'direct'),
  ('Nagaland District Court - Kiphire', 'https://districts.ecourts.gov.in/kiphire', 'court', 'direct'),
  ('Nagaland District Court - Kohima', 'https://districts.ecourts.gov.in/kohima', 'court', 'direct'),
  ('Nagaland District Court - Longleng', 'https://districts.ecourts.gov.in/longleng', 'court', 'direct'),
  ('Nagaland District Court - Mokokchung', 'https://districts.ecourts.gov.in/mokokchung', 'court', 'direct'),
  ('Nagaland District Court - Mon', 'https://districts.ecourts.gov.in/mon', 'court', 'direct'),
  ('Nagaland District Court - Peren', 'https://districts.ecourts.gov.in/peren', 'court', 'direct'),
  ('Nagaland District Court - Phek', 'https://districts.ecourts.gov.in/phek', 'court', 'direct'),
  ('Nagaland District Court - Tuensang', 'https://districts.ecourts.gov.in/tuensang', 'court', 'direct'),
  ('Nagaland District Court - Wokha', 'https://districts.ecourts.gov.in/wokha', 'court', 'direct'),
  ('Nagaland District Court - Zunheboto', 'https://districts.ecourts.gov.in/zunheboto', 'court', 'direct'),
  ('Odisha District Court - Angul', 'https://districts.ecourts.gov.in/angul', 'court', 'direct'),
  ('Odisha District Court - Balangir', 'https://districts.ecourts.gov.in/balangir', 'court', 'direct'),
  ('Odisha District Court - Balasore', 'https://districts.ecourts.gov.in/balasore', 'court', 'direct'),
  ('Odisha District Court - Bargarh', 'https://districts.ecourts.gov.in/bargarh', 'court', 'direct'),
  ('Odisha District Court - Bhadrak', 'https://districts.ecourts.gov.in/bhadrak', 'court', 'direct'),
  ('Odisha District Court - Boudh', 'https://districts.ecourts.gov.in/boudh', 'court', 'direct'),
  ('Odisha District Court - Cuttack', 'https://districts.ecourts.gov.in/cuttack', 'court', 'direct'),
  ('Odisha District Court - Deogarh', 'https://districts.ecourts.gov.in/deogarh', 'court', 'direct'),
  ('Odisha District Court - Dhenkanal', 'https://districts.ecourts.gov.in/dhenkanal', 'court', 'direct'),
  ('Odisha District Court - Gajapati', 'https://districts.ecourts.gov.in/gajapati', 'court', 'direct'),
  ('Odisha District Court - Ganjamr', 'https://districts.ecourts.gov.in/ganjamr', 'court', 'direct'),
  ('Odisha District Court - Jaga', 'https://districts.ecourts.gov.in/jaga', 'court', 'direct'),
  ('Odisha District Court - Jajptsinghpurur', 'https://districts.ecourts.gov.in/jajptsinghpurur', 'court', 'direct'),
  ('Odisha District Court - Jharsuguda', 'https://districts.ecourts.gov.in/jharsuguda', 'court', 'direct'),
  ('Odisha District Court - Kalahandi', 'https://districts.ecourts.gov.in/kalahandi', 'court', 'direct'),
  ('Odisha District Court - Kandhamal', 'https://districts.ecourts.gov.in/kandhamal', 'court', 'direct'),
  ('Odisha District Court - Kendrapara', 'https://districts.ecourts.gov.in/kendrapara', 'court', 'direct'),
  ('Odisha District Court - Keonjhar', 'https://districts.ecourts.gov.in/keonjhar', 'court', 'direct'),
  ('Odisha District Court - Khordha', 'https://districts.ecourts.gov.in/khordha', 'court', 'direct'),
  ('Odisha District Court - Koraput', 'https://districts.ecourts.gov.in/koraput', 'court', 'direct'),
  ('Odisha District Court - Malkangiri', 'https://districts.ecourts.gov.in/malkangiri', 'court', 'direct'),
  ('Odisha District Court - Mayurbhanj', 'https://districts.ecourts.gov.in/mayurbhanj', 'court', 'direct'),
  ('Odisha District Court - Nabarangpur', 'https://districts.ecourts.gov.in/nabarangpur', 'court', 'direct'),
  ('Odisha District Court - Nayagarh', 'https://districts.ecourts.gov.in/nayagarh', 'court', 'direct'),
  ('Odisha District Court - Nuapada', 'https://districts.ecourts.gov.in/nuapada', 'court', 'direct'),
  ('Odisha District Court - Puri', 'https://districts.ecourts.gov.in/puri', 'court', 'direct'),
  ('Odisha District Court - Rayagada', 'https://districts.ecourts.gov.in/rayagada', 'court', 'direct'),
  ('Odisha District Court - Sambalpur', 'https://districts.ecourts.gov.in/sambalpur', 'court', 'direct'),
  ('Odisha District Court - Subarnapur', 'https://districts.ecourts.gov.in/subarnapur', 'court', 'direct'),
  ('Odisha District Court - Sundargarh', 'https://districts.ecourts.gov.in/sundargarh', 'court', 'direct'),
  ('Punjab District Court - Amritsar', 'https://districts.ecourts.gov.in/amritsar', 'court', 'direct'),
  ('Punjab District Court - Barnala', 'https://districts.ecourts.gov.in/barnala', 'court', 'direct'),
  ('Punjab District Court - Bathinda', 'https://districts.ecourts.gov.in/bathinda', 'court', 'direct'),
  ('Punjab District Court - Faridkot', 'https://districts.ecourts.gov.in/faridkot', 'court', 'direct'),
  ('Punjab District Court - Fatehgarhsahib', 'https://districts.ecourts.gov.in/fatehgarhsahib', 'court', 'direct'),
  ('Punjab District Court - Fazilka', 'https://districts.ecourts.gov.in/fazilka', 'court', 'direct'),
  ('Punjab District Court - Ferozepur', 'https://districts.ecourts.gov.in/ferozepur', 'court', 'direct'),
  ('Punjab District Court - Gurdaspur', 'https://districts.ecourts.gov.in/gurdaspur', 'court', 'direct'),
  ('Punjab District Court - Hoshiarpur', 'https://districts.ecourts.gov.in/hoshiarpur', 'court', 'direct'),
  ('Punjab District Court - Jalandhar', 'https://districts.ecourts.gov.in/jalandhar', 'court', 'direct'),
  ('Punjab District Court - Kapurthala', 'https://districts.ecourts.gov.in/kapurthala', 'court', 'direct'),
  ('Punjab District Court - Ludhiana', 'https://districts.ecourts.gov.in/ludhiana', 'court', 'direct'),
  ('Punjab District Court - Mansa', 'https://districts.ecourts.gov.in/mansa', 'court', 'direct'),
  ('Punjab District Court - Moga', 'https://districts.ecourts.gov.in/moga', 'court', 'direct'),
  ('Punjab District Court - Muktsar', 'https://districts.ecourts.gov.in/muktsar', 'court', 'direct'),
  ('Punjab District Court - Nawanshahr', 'https://districts.ecourts.gov.in/nawanshahr', 'court', 'direct'),
  ('Punjab District Court - Pathankot', 'https://districts.ecourts.gov.in/pathankot', 'court', 'direct'),
  ('Punjab District Court - Patiala', 'https://districts.ecourts.gov.in/patiala', 'court', 'direct'),
  ('Punjab District Court - Rupnagar', 'https://districts.ecourts.gov.in/rupnagar', 'court', 'direct'),
  ('Punjab District Court - Sangrur', 'https://districts.ecourts.gov.in/sangrur', 'court', 'direct'),
  ('Punjab District Court - Sasnagar', 'https://districts.ecourts.gov.in/sasnagar', 'court', 'direct'),
  ('Punjab District Court - Tarntaran', 'https://districts.ecourts.gov.in/tarntaran', 'court', 'direct'),
  ('Rajasthan District Court - Ajmer', 'https://districts.ecourts.gov.in/ajmer', 'court', 'direct'),
  ('Rajasthan District Court - Alwar', 'https://districts.ecourts.gov.in/alwar', 'court', 'direct'),
  ('Rajasthan District Court - Banswara', 'https://districts.ecourts.gov.in/banswara', 'court', 'direct'),
  ('Rajasthan District Court - Baran', 'https://districts.ecourts.gov.in/baran', 'court', 'direct'),
  ('Rajasthan District Court - Barmer', 'https://districts.ecourts.gov.in/barmer', 'court', 'direct'),
  ('Rajasthan District Court - Bharatpur', 'https://districts.ecourts.gov.in/bharatpur', 'court', 'direct'),
  ('Rajasthan District Court - Bhilwara', 'https://districts.ecourts.gov.in/bhilwara', 'court', 'direct'),
  ('Rajasthan District Court - Bikaner', 'https://districts.ecourts.gov.in/bikaner', 'court', 'direct'),
  ('Rajasthan District Court - Bundi', 'https://districts.ecourts.gov.in/bundi', 'court', 'direct'),
  ('Rajasthan District Court - Chittorgarh', 'https://districts.ecourts.gov.in/chittorgarh', 'court', 'direct'),
  ('Rajasthan District Court - Churu', 'https://districts.ecourts.gov.in/churu', 'court', 'direct'),
  ('Rajasthan District Court - Dausa', 'https://districts.ecourts.gov.in/dausa', 'court', 'direct'),
  ('Rajasthan District Court - Dholpur', 'https://districts.ecourts.gov.in/dholpur', 'court', 'direct'),
  ('Rajasthan District Court - Dungarpur', 'https://districts.ecourts.gov.in/dungarpur', 'court', 'direct'),
  ('Rajasthan District Court - Hanumangarh', 'https://districts.ecourts.gov.in/hanumangarh', 'court', 'direct'),
  ('Rajasthan District Court - Jaipur', 'https://districts.ecourts.gov.in/jaipur', 'court', 'direct'),
  ('Rajasthan District Court - Jaisalmer', 'https://districts.ecourts.gov.in/jaisalmer', 'court', 'direct'),
  ('Rajasthan District Court - Jalore', 'https://districts.ecourts.gov.in/jalore', 'court', 'direct'),
  ('Rajasthan District Court - Jhalawar', 'https://districts.ecourts.gov.in/jhalawar', 'court', 'direct'),
  ('Rajasthan District Court - Jhunjhunu', 'https://districts.ecourts.gov.in/jhunjhunu', 'court', 'direct'),
  ('Rajasthan District Court - Jodhpur', 'https://districts.ecourts.gov.in/jodhpur', 'court', 'direct'),
  ('Rajasthan District Court - Karauli', 'https://districts.ecourts.gov.in/karauli', 'court', 'direct'),
  ('Rajasthan District Court - Kota', 'https://districts.ecourts.gov.in/kota', 'court', 'direct'),
  ('Rajasthan District Court - Nagaur', 'https://districts.ecourts.gov.in/nagaur', 'court', 'direct'),
  ('Rajasthan District Court - Pali', 'https://districts.ecourts.gov.in/pali', 'court', 'direct'),
  ('Rajasthan District Court - Pratapgarhrj', 'https://districts.ecourts.gov.in/pratapgarhrj', 'court', 'direct'),
  ('Rajasthan District Court - Rajsamand', 'https://districts.ecourts.gov.in/rajsamand', 'court', 'direct'),
  ('Rajasthan District Court - Sawaimadhopur', 'https://districts.ecourts.gov.in/sawaimadhopur', 'court', 'direct'),
  ('Rajasthan District Court - Sikar', 'https://districts.ecourts.gov.in/sikar', 'court', 'direct'),
  ('Rajasthan District Court - Sirohi', 'https://districts.ecourts.gov.in/sirohi', 'court', 'direct'),
  ('Rajasthan District Court - Sriganganagar', 'https://districts.ecourts.gov.in/sriganganagar', 'court', 'direct'),
  ('Rajasthan District Court - Tonk', 'https://districts.ecourts.gov.in/tonk', 'court', 'direct'),
  ('Rajasthan District Court - Udaipur', 'https://districts.ecourts.gov.in/udaipur', 'court', 'direct'),
  ('Tamil Nadu District Court - Ariyalur', 'https://districts.ecourts.gov.in/ariyalur', 'court', 'direct'),
  ('Tamil Nadu District Court - Chennai', 'https://districts.ecourts.gov.in/chennai', 'court', 'direct'),
  ('Tamil Nadu District Court - Coimbatore', 'https://districts.ecourts.gov.in/coimbatore', 'court', 'direct'),
  ('Tamil Nadu District Court - Cuddalore', 'https://districts.ecourts.gov.in/cuddalore', 'court', 'direct'),
  ('Tamil Nadu District Court - Dharmapuri', 'https://districts.ecourts.gov.in/dharmapuri', 'court', 'direct'),
  ('Tamil Nadu District Court - Dindigul', 'https://districts.ecourts.gov.in/dindigul', 'court', 'direct'),
  ('Tamil Nadu District Court - Erode', 'https://districts.ecourts.gov.in/erode', 'court', 'direct'),
  ('Tamil Nadu District Court - Kancheepuram', 'https://districts.ecourts.gov.in/kancheepuram', 'court', 'direct'),
  ('Tamil Nadu District Court - Karur', 'https://districts.ecourts.gov.in/karur', 'court', 'direct'),
  ('Tamil Nadu District Court - Krishnagiri', 'https://districts.ecourts.gov.in/krishnagiri', 'court', 'direct'),
  ('Tamil Nadu District Court - Madurai', 'https://districts.ecourts.gov.in/madurai', 'court', 'direct'),
  ('Tamil Nadu District Court - Nagapattinam', 'https://districts.ecourts.gov.in/nagapattinam', 'court', 'direct'),
  ('Tamil Nadu District Court - Namakkal', 'https://districts.ecourts.gov.in/namakkal', 'court', 'direct'),
  ('Tamil Nadu District Court - Perambalur', 'https://districts.ecourts.gov.in/perambalur', 'court', 'direct'),
  ('Tamil Nadu District Court - Pudukkottaim', 'https://districts.ecourts.gov.in/pudukkottaim', 'court', 'direct'),
  ('Tamil Nadu District Court - Ramana', 'https://districts.ecourts.gov.in/ramana', 'court', 'direct'),
  ('Tamil Nadu District Court - Salem', 'https://districts.ecourts.gov.in/salem', 'court', 'direct'),
  ('Tamil Nadu District Court - Sivagathapuramnga', 'https://districts.ecourts.gov.in/sivagathapuramnga', 'court', 'direct'),
  ('Tamil Nadu District Court - Thanjavur', 'https://districts.ecourts.gov.in/thanjavur', 'court', 'direct'),
  ('Tamil Nadu District Court - Theni', 'https://districts.ecourts.gov.in/theni', 'court', 'direct'),
  ('Tamil Nadu District Court - Thoothukudi', 'https://districts.ecourts.gov.in/thoothukudi', 'court', 'direct'),
  ('Tamil Nadu District Court - Tiruchirappalli', 'https://districts.ecourts.gov.in/tiruchirappalli', 'court', 'direct'),
  ('Tamil Nadu District Court - Tirunelveli', 'https://districts.ecourts.gov.in/tirunelveli', 'court', 'direct'),
  ('Tamil Nadu District Court - Tiruppur', 'https://districts.ecourts.gov.in/tiruppur', 'court', 'direct'),
  ('Tamil Nadu District Court - Tiruvallur', 'https://districts.ecourts.gov.in/tiruvallur', 'court', 'direct'),
  ('Tamil Nadu District Court - Tiruvannamalai', 'https://districts.ecourts.gov.in/tiruvannamalai', 'court', 'direct'),
  ('Tamil Nadu District Court - Tiruvarur', 'https://districts.ecourts.gov.in/tiruvarur', 'court', 'direct'),
  ('Tamil Nadu District Court - Vellore', 'https://districts.ecourts.gov.in/vellore', 'court', 'direct'),
  ('Tamil Nadu District Court - Viluppuram', 'https://districts.ecourts.gov.in/viluppuram', 'court', 'direct'),
  ('Tamil Nadu District Court - Virudhunagar', 'https://districts.ecourts.gov.in/virudhunagar', 'court', 'direct'),
  ('Tamil Nadu District Court - Kallakurichi', 'https://districts.ecourts.gov.in/kallakurichi', 'court', 'direct'),
  ('Tamil Nadu District Court - Tenkasi', 'https://districts.ecourts.gov.in/tenkasi', 'court', 'direct'),
  ('Telangana District Court - Adilabad', 'https://districts.ecourts.gov.in/adilabad', 'court', 'direct'),
  ('Telangana District Court - Bhadradrikothagudem', 'https://districts.ecourts.gov.in/bhadradrikothagudem', 'court', 'direct'),
  ('Telangana District Court - Hyderabad', 'https://districts.ecourts.gov.in/hyderabad', 'court', 'direct'),
  ('Telangana District Court - Jagtial', 'https://districts.ecourts.gov.in/jagtial', 'court', 'direct'),
  ('Telangana District Court - Jangaon', 'https://districts.ecourts.gov.in/jangaon', 'court', 'direct'),
  ('Telangana District Court - Jayashankar', 'https://districts.ecourts.gov.in/jayashankar', 'court', 'direct'),
  ('Telangana District Court - Jogulambagabhupalpallydwal', 'https://districts.ecourts.gov.in/jogulambagabhupalpallydwal', 'court', 'direct'),
  ('Telangana District Court - Kamareddy', 'https://districts.ecourts.gov.in/kamareddy', 'court', 'direct'),
  ('Telangana District Court - Karimnagar', 'https://districts.ecourts.gov.in/karimnagar', 'court', 'direct'),
  ('Telangana District Court - Khammam', 'https://districts.ecourts.gov.in/khammam', 'court', 'direct'),
  ('Telangana District Court - Komarambheem', 'https://districts.ecourts.gov.in/komarambheem', 'court', 'direct'),
  ('Telangana District Court - Mahabubabad', 'https://districts.ecourts.gov.in/mahabubabad', 'court', 'direct'),
  ('Telangana District Court - Mahbubnagar', 'https://districts.ecourts.gov.in/mahbubnagar', 'court', 'direct'),
  ('Telangana District Court - Mancherial', 'https://districts.ecourts.gov.in/mancherial', 'court', 'direct'),
  ('Telangana District Court - Medak', 'https://districts.ecourts.gov.in/medak', 'court', 'direct'),
  ('Telangana District Court - Medchalmalkajgiri', 'https://districts.ecourts.gov.in/medchalmalkajgiri', 'court', 'direct'),
  ('Telangana District Court - Mulugu', 'https://districts.ecourts.gov.in/mulugu', 'court', 'direct'),
  ('Telangana District Court - Nagarkurnool', 'https://districts.ecourts.gov.in/nagarkurnool', 'court', 'direct'),
  ('Telangana District Court - Nalgonda', 'https://districts.ecourts.gov.in/nalgonda', 'court', 'direct'),
  ('Telangana District Court - Narayanpet', 'https://districts.ecourts.gov.in/narayanpet', 'court', 'direct'),
  ('Telangana District Court - Nirmal', 'https://districts.ecourts.gov.in/nirmal', 'court', 'direct'),
  ('Telangana District Court - Nizamabad', 'https://districts.ecourts.gov.in/nizamabad', 'court', 'direct'),
  ('Telangana District Court - Peddapalli', 'https://districts.ecourts.gov.in/peddapalli', 'court', 'direct'),
  ('Telangana District Court - Rajannasircilla', 'https://districts.ecourts.gov.in/rajannasircilla', 'court', 'direct'),
  ('Telangana District Court - Rangareddy', 'https://districts.ecourts.gov.in/rangareddy', 'court', 'direct'),
  ('Telangana District Court - Sangareddy', 'https://districts.ecourts.gov.in/sangareddy', 'court', 'direct'),
  ('Telangana District Court - Siddipet', 'https://districts.ecourts.gov.in/siddipet', 'court', 'direct'),
  ('Telangana District Court - Suryapet', 'https://districts.ecourts.gov.in/suryapet', 'court', 'direct'),
  ('Telangana District Court - Vikarabad', 'https://districts.ecourts.gov.in/vikarabad', 'court', 'direct'),
  ('Telangana District Court - Wanaparthy', 'https://districts.ecourts.gov.in/wanaparthy', 'court', 'direct'),
  ('Telangana District Court - Warangalrural', 'https://districts.ecourts.gov.in/warangalrural', 'court', 'direct'),
  ('Telangana District Court - Warangalurban', 'https://districts.ecourts.gov.in/warangalurban', 'court', 'direct'),
  ('Telangana District Court - Yadadribhuvanagiri', 'https://districts.ecourts.gov.in/yadadribhuvanagiri', 'court', 'direct'),
  ('Tripura District Court - Dhalai', 'https://districts.ecourts.gov.in/dhalai', 'court', 'direct'),
  ('Tripura District Court - Gomati', 'https://districts.ecourts.gov.in/gomati', 'court', 'direct'),
  ('Tripura District Court - Khowai', 'https://districts.ecourts.gov.in/khowai', 'court', 'direct'),
  ('Tripura District Court - Northtripura', 'https://districts.ecourts.gov.in/northtripura', 'court', 'direct'),
  ('Tripura District Court - Sepahijala', 'https://districts.ecourts.gov.in/sepahijala', 'court', 'direct'),
  ('Tripura District Court - Southtripura', 'https://districts.ecourts.gov.in/southtripura', 'court', 'direct'),
  ('Tripura District Court - Unakoti', 'https://districts.ecourts.gov.in/unakoti', 'court', 'direct'),
  ('Tripura District Court - Westtripura', 'https://districts.ecourts.gov.in/westtripura', 'court', 'direct'),
  ('Uttar Pradesh District Court - Agra', 'https://districts.ecourts.gov.in/agra', 'court', 'direct'),
  ('Uttar Pradesh District Court - Aligarh', 'https://districts.ecourts.gov.in/aligarh', 'court', 'direct'),
  ('Uttar Pradesh District Court - Allahabad', 'https://districts.ecourts.gov.in/allahabad', 'court', 'direct'),
  ('Uttar Pradesh District Court - Ambedkarnagar', 'https://districts.ecourts.gov.in/ambedkarnagar', 'court', 'direct'),
  ('Uttar Pradesh District Court - Amethi', 'https://districts.ecourts.gov.in/amethi', 'court', 'direct'),
  ('Uttar Pradesh District Court - Amroha', 'https://districts.ecourts.gov.in/amroha', 'court', 'direct'),
  ('Uttar Pradesh District Court - Auraiya', 'https://districts.ecourts.gov.in/auraiya', 'court', 'direct'),
  ('Uttar Pradesh District Court - Azamgarh', 'https://districts.ecourts.gov.in/azamgarh', 'court', 'direct'),
  ('Uttar Pradesh District Court - Baghpat', 'https://districts.ecourts.gov.in/baghpat', 'court', 'direct'),
  ('Uttar Pradesh District Court - Bahraich', 'https://districts.ecourts.gov.in/bahraich', 'court', 'direct'),
  ('Uttar Pradesh District Court - Ballia', 'https://districts.ecourts.gov.in/ballia', 'court', 'direct'),
  ('Uttar Pradesh District Court - Balrampurup', 'https://districts.ecourts.gov.in/balrampurup', 'court', 'direct'),
  ('Uttar Pradesh District Court - Banda', 'https://districts.ecourts.gov.in/banda', 'court', 'direct'),
  ('Uttar Pradesh District Court - Barabanki', 'https://districts.ecourts.gov.in/barabanki', 'court', 'direct'),
  ('Uttar Pradesh District Court - Bareilly', 'https://districts.ecourts.gov.in/bareilly', 'court', 'direct'),
  ('Uttar Pradesh District Court - Basti', 'https://districts.ecourts.gov.in/basti', 'court', 'direct'),
  ('Uttar Pradesh District Court - Bijnor', 'https://districts.ecourts.gov.in/bijnor', 'court', 'direct'),
  ('Uttar Pradesh District Court - Budaun', 'https://districts.ecourts.gov.in/budaun', 'court', 'direct'),
  ('Uttar Pradesh District Court - Bulandshahr', 'https://districts.ecourts.gov.in/bulandshahr', 'court', 'direct'),
  ('Uttar Pradesh District Court - Chandauli', 'https://districts.ecourts.gov.in/chandauli', 'court', 'direct'),
  ('Uttar Pradesh District Court - Chitrakoot', 'https://districts.ecourts.gov.in/chitrakoot', 'court', 'direct'),
  ('Uttar Pradesh District Court - Deoria', 'https://districts.ecourts.gov.in/deoria', 'court', 'direct'),
  ('Uttar Pradesh District Court - Etah', 'https://districts.ecourts.gov.in/etah', 'court', 'direct'),
  ('Uttar Pradesh District Court - Etawah', 'https://districts.ecourts.gov.in/etawah', 'court', 'direct'),
  ('Uttar Pradesh District Court - Farrukhabad', 'https://districts.ecourts.gov.in/farrukhabad', 'court', 'direct'),
  ('Uttar Pradesh District Court - Fatehpur', 'https://districts.ecourts.gov.in/fatehpur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Firozabad', 'https://districts.ecourts.gov.in/firozabad', 'court', 'direct'),
  ('Uttar Pradesh District Court - Gautambuddhanagar', 'https://districts.ecourts.gov.in/gautambuddhanagar', 'court', 'direct'),
  ('Uttar Pradesh District Court - Ghaziabad', 'https://districts.ecourts.gov.in/ghaziabad', 'court', 'direct'),
  ('Uttar Pradesh District Court - Ghazipur', 'https://districts.ecourts.gov.in/ghazipur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Gonda', 'https://districts.ecourts.gov.in/gonda', 'court', 'direct'),
  ('Uttar Pradesh District Court - Gorakhpur', 'https://districts.ecourts.gov.in/gorakhpur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Hamirpurup', 'https://districts.ecourts.gov.in/hamirpurup', 'court', 'direct'),
  ('Uttar Pradesh District Court - Hapur', 'https://districts.ecourts.gov.in/hapur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Hardoi', 'https://districts.ecourts.gov.in/hardoi', 'court', 'direct'),
  ('Uttar Pradesh District Court - Hathras', 'https://districts.ecourts.gov.in/hathras', 'court', 'direct'),
  ('Uttar Pradesh District Court - Jalaun', 'https://districts.ecourts.gov.in/jalaun', 'court', 'direct'),
  ('Uttar Pradesh District Court - Jaunpur', 'https://districts.ecourts.gov.in/jaunpur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Jhansi', 'https://districts.ecourts.gov.in/jhansi', 'court', 'direct'),
  ('Uttar Pradesh District Court - Kannauj', 'https://districts.ecourts.gov.in/kannauj', 'court', 'direct'),
  ('Uttar Pradesh District Court - Kanpurdehat', 'https://districts.ecourts.gov.in/kanpurdehat', 'court', 'direct'),
  ('Uttar Pradesh District Court - Kanpurnagar', 'https://districts.ecourts.gov.in/kanpurnagar', 'court', 'direct'),
  ('Uttar Pradesh District Court - Kasganj', 'https://districts.ecourts.gov.in/kasganj', 'court', 'direct'),
  ('Uttar Pradesh District Court - Kaushambi', 'https://districts.ecourts.gov.in/kaushambi', 'court', 'direct'),
  ('Uttar Pradesh District Court - Kushinagar', 'https://districts.ecourts.gov.in/kushinagar', 'court', 'direct'),
  ('Uttar Pradesh District Court - Lakhimpurkheri', 'https://districts.ecourts.gov.in/lakhimpurkheri', 'court', 'direct'),
  ('Uttar Pradesh District Court - Lalitpur', 'https://districts.ecourts.gov.in/lalitpur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Lucknow', 'https://districts.ecourts.gov.in/lucknow', 'court', 'direct'),
  ('Uttar Pradesh District Court - Maharajganj', 'https://districts.ecourts.gov.in/maharajganj', 'court', 'direct'),
  ('Uttar Pradesh District Court - Mahoba', 'https://districts.ecourts.gov.in/mahoba', 'court', 'direct'),
  ('Uttar Pradesh District Court - Mainpuri', 'https://districts.ecourts.gov.in/mainpuri', 'court', 'direct'),
  ('Uttar Pradesh District Court - Mathura', 'https://districts.ecourts.gov.in/mathura', 'court', 'direct'),
  ('Uttar Pradesh District Court - Mau', 'https://districts.ecourts.gov.in/mau', 'court', 'direct'),
  ('Uttar Pradesh District Court - Meerut', 'https://districts.ecourts.gov.in/meerut', 'court', 'direct'),
  ('Uttar Pradesh District Court - Mirzapur', 'https://districts.ecourts.gov.in/mirzapur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Moradabad', 'https://districts.ecourts.gov.in/moradabad', 'court', 'direct'),
  ('Uttar Pradesh District Court - Muzaffarnagar', 'https://districts.ecourts.gov.in/muzaffarnagar', 'court', 'direct'),
  ('Uttar Pradesh District Court - Pilibhit', 'https://districts.ecourts.gov.in/pilibhit', 'court', 'direct'),
  ('Uttar Pradesh District Court - Pratapgarh', 'https://districts.ecourts.gov.in/pratapgarh', 'court', 'direct'),
  ('Uttar Pradesh District Court - Raebareli', 'https://districts.ecourts.gov.in/raebareli', 'court', 'direct'),
  ('Uttar Pradesh District Court - Rampur', 'https://districts.ecourts.gov.in/rampur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Saharanpur', 'https://districts.ecourts.gov.in/saharanpur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Sambhal', 'https://districts.ecourts.gov.in/sambhal', 'court', 'direct'),
  ('Uttar Pradesh District Court - Santkabirnagar', 'https://districts.ecourts.gov.in/santkabirnagar', 'court', 'direct'),
  ('Uttar Pradesh District Court - Shahjahanpur', 'https://districts.ecourts.gov.in/shahjahanpur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Shamli', 'https://districts.ecourts.gov.in/shamli', 'court', 'direct'),
  ('Uttar Pradesh District Court - Shrawasti', 'https://districts.ecourts.gov.in/shrawasti', 'court', 'direct'),
  ('Uttar Pradesh District Court - Siddharthnagar', 'https://districts.ecourts.gov.in/siddharthnagar', 'court', 'direct'),
  ('Uttar Pradesh District Court - Sitapur', 'https://districts.ecourts.gov.in/sitapur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Sonbhadra', 'https://districts.ecourts.gov.in/sonbhadra', 'court', 'direct'),
  ('Uttar Pradesh District Court - Sultanpur', 'https://districts.ecourts.gov.in/sultanpur', 'court', 'direct'),
  ('Uttar Pradesh District Court - Unnao', 'https://districts.ecourts.gov.in/unnao', 'court', 'direct'),
  ('Uttar Pradesh District Court - Varanasi', 'https://districts.ecourts.gov.in/varanasi', 'court', 'direct'),
  ('Uttar Pradesh District Court - Faizabad', 'https://districts.ecourts.gov.in/faizabad', 'court', 'direct'),
  ('Uttar Pradesh District Court - Santravidasnagar', 'https://districts.ecourts.gov.in/santravidasnagar', 'court', 'direct'),
  ('Uttarakhand District Court - Almora', 'https://districts.ecourts.gov.in/almora', 'court', 'direct'),
  ('Uttarakhand District Court - Bageshwar', 'https://districts.ecourts.gov.in/bageshwar', 'court', 'direct'),
  ('Uttarakhand District Court - Chamoli', 'https://districts.ecourts.gov.in/chamoli', 'court', 'direct'),
  ('Uttarakhand District Court - Champawat', 'https://districts.ecourts.gov.in/champawat', 'court', 'direct'),
  ('Uttarakhand District Court - Dehradun', 'https://districts.ecourts.gov.in/dehradun', 'court', 'direct'),
  ('Uttarakhand District Court - Haridwar', 'https://districts.ecourts.gov.in/haridwar', 'court', 'direct'),
  ('Uttarakhand District Court - Nainital', 'https://districts.ecourts.gov.in/nainital', 'court', 'direct'),
  ('Uttarakhand District Court - Paurigarhwal', 'https://districts.ecourts.gov.in/paurigarhwal', 'court', 'direct'),
  ('Uttarakhand District Court - Pithoragarh', 'https://districts.ecourts.gov.in/pithoragarh', 'court', 'direct'),
  ('Uttarakhand District Court - Rudraprayag', 'https://districts.ecourts.gov.in/rudraprayag', 'court', 'direct'),
  ('Uttarakhand District Court - Tehrigarhwal', 'https://districts.ecourts.gov.in/tehrigarhwal', 'court', 'direct'),
  ('Uttarakhand District Court - Udhamsinghnagar', 'https://districts.ecourts.gov.in/udhamsinghnagar', 'court', 'direct'),
  ('Uttarakhand District Court - Uttarkashi', 'https://districts.ecourts.gov.in/uttarkashi', 'court', 'direct'),
  ('West Bengal District Court - Alipurduar', 'https://districts.ecourts.gov.in/alipurduar', 'court', 'direct'),
  ('West Bengal District Court - Bankura', 'https://districts.ecourts.gov.in/bankura', 'court', 'direct'),
  ('West Bengal District Court - Birbhum', 'https://districts.ecourts.gov.in/birbhum', 'court', 'direct'),
  ('West Bengal District Court - Coochbehar', 'https://districts.ecourts.gov.in/coochbehar', 'court', 'direct'),
  ('West Bengal District Court - Dakshindinajpur', 'https://districts.ecourts.gov.in/dakshindinajpur', 'court', 'direct'),
  ('West Bengal District Court - Darjeeling', 'https://districts.ecourts.gov.in/darjeeling', 'court', 'direct'),
  ('West Bengal District Court - Hooghly', 'https://districts.ecourts.gov.in/hooghly', 'court', 'direct'),
  ('West Bengal District Court - Howrah', 'https://districts.ecourts.gov.in/howrah', 'court', 'direct'),
  ('West Bengal District Court - Jalpaiguri', 'https://districts.ecourts.gov.in/jalpaiguri', 'court', 'direct'),
  ('West Bengal District Court - Jhargram', 'https://districts.ecourts.gov.in/jhargram', 'court', 'direct'),
  ('West Bengal District Court - Kalimpong', 'https://districts.ecourts.gov.in/kalimpong', 'court', 'direct'),
  ('West Bengal District Court - Kolkata', 'https://districts.ecourts.gov.in/kolkata', 'court', 'direct'),
  ('West Bengal District Court - Malda', 'https://districts.ecourts.gov.in/malda', 'court', 'direct'),
  ('West Bengal District Court - Murshidabad', 'https://districts.ecourts.gov.in/murshidabad', 'court', 'direct'),
  ('West Bengal District Court - Nadia', 'https://districts.ecourts.gov.in/nadia', 'court', 'direct'),
  ('West Bengal District Court - North24Parganas', 'https://districts.ecourts.gov.in/north24parganas', 'court', 'direct'),
  ('West Bengal District Court - Paschi', 'https://districts.ecourts.gov.in/paschi', 'court', 'direct'),
  ('West Bengal District Court - Paschimbardhamanmmedinipur', 'https://districts.ecourts.gov.in/paschimbardhamanmmedinipur', 'court', 'direct'),
  ('West Bengal District Court - Purbabardhaman', 'https://districts.ecourts.gov.in/purbabardhaman', 'court', 'direct'),
  ('West Bengal District Court - Purbamedinipur', 'https://districts.ecourts.gov.in/purbamedinipur', 'court', 'direct'),
  ('West Bengal District Court - Purulia', 'https://districts.ecourts.gov.in/purulia', 'court', 'direct'),
  ('West Bengal District Court - South24Parganas', 'https://districts.ecourts.gov.in/south24parganas', 'court', 'direct'),
  ('West Bengal District Court - Uttardinajpur', 'https://districts.ecourts.gov.in/uttardinajpur', 'court', 'direct'),
  ('Chandigarh District Court - Chandigarh', 'https://districts.ecourts.gov.in/chandigarh', 'court', 'direct'),
  ('Andaman & Nicobar District Court - Andamanandnicobar', 'https://districts.ecourts.gov.in/andamanandnicobar', 'court', 'direct'),
  ('Dadra & Nagar Haveli and Daman & Diu District Court - Dadraandnagarhaveli', 'https://districts.ecourts.gov.in/dadraandnagarhaveli', 'court', 'direct'),
  ('Dadra & Nagar Haveli and Daman & Diu District Court - Damananddiu', 'https://districts.ecourts.gov.in/damananddiu', 'court', 'direct'),
  ('Delhi District Court - Centraldelhi', 'https://districts.ecourts.gov.in/centraldelhi', 'court', 'direct'),
  ('Delhi District Court - Eastdelhi', 'https://districts.ecourts.gov.in/eastdelhi', 'court', 'direct'),
  ('Delhi District Court - Newdelhi', 'https://districts.ecourts.gov.in/newdelhi', 'court', 'direct'),
  ('Delhi District Court - Northdelhi', 'https://districts.ecourts.gov.in/northdelhi', 'court', 'direct'),
  ('Delhi District Court - Northeastdelhi', 'https://districts.ecourts.gov.in/northeastdelhi', 'court', 'direct'),
  ('Delhi District Court - Northwestdelhi', 'https://districts.ecourts.gov.in/northwestdelhi', 'court', 'direct'),
  ('Delhi District Court - Shahdara', 'https://districts.ecourts.gov.in/shahdara', 'court', 'direct'),
  ('Delhi District Court - Southdelhi', 'https://districts.ecourts.gov.in/southdelhi', 'court', 'direct'),
  ('Delhi District Court - Southeastdelhi', 'https://districts.ecourts.gov.in/southeastdelhi', 'court', 'direct'),
  ('Delhi District Court - Southwestdelhi', 'https://districts.ecourts.gov.in/southwestdelhi', 'court', 'direct'),
  ('Delhi District Court - Westdelhi', 'https://districts.ecourts.gov.in/westdelhi', 'court', 'direct'),
  ('Lakshadweep District Court - Lakshadweep', 'https://districts.ecourts.gov.in/lakshadweep', 'court', 'direct'),
  ('Puducherry District Court - Puducherry', 'https://districts.ecourts.gov.in/puducherry', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Anantnag', 'https://districts.ecourts.gov.in/anantnag', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Bandipora', 'https://districts.ecourts.gov.in/bandipora', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Baramulla', 'https://districts.ecourts.gov.in/baramulla', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Budgam', 'https://districts.ecourts.gov.in/budgam', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Doda', 'https://districts.ecourts.gov.in/doda', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Ganderbal', 'https://districts.ecourts.gov.in/ganderbal', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Jammu', 'https://districts.ecourts.gov.in/jammu', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Kathua', 'https://districts.ecourts.gov.in/kathua', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Kishtwar', 'https://districts.ecourts.gov.in/kishtwar', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Kulgam', 'https://districts.ecourts.gov.in/kulgam', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Kupwara', 'https://districts.ecourts.gov.in/kupwara', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Poonch', 'https://districts.ecourts.gov.in/poonch', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Pulwama', 'https://districts.ecourts.gov.in/pulwama', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Rajouri', 'https://districts.ecourts.gov.in/rajouri', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Ramban', 'https://districts.ecourts.gov.in/ramban', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Reasi', 'https://districts.ecourts.gov.in/reasi', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Samba', 'https://districts.ecourts.gov.in/samba', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Shopian', 'https://districts.ecourts.gov.in/shopian', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Srinagar', 'https://districts.ecourts.gov.in/srinagar', 'court', 'direct'),
  ('Jammu & Kashmir District Court - Udhampur', 'https://districts.ecourts.gov.in/udhampur', 'court', 'direct')
ON CONFLICT (url) DO NOTHING;

-- Totals: 84 curated + 26 SC/High Courts + 675 district courts = 785 sources